In [1]:
import numpy as np
import pandas as pd

In [2]:
## series of 1-d array

In [4]:
s = pd.Series([10,20,30,40])

In [5]:
print(s)

0    10
1    20
2    30
3    40
dtype: int64

In [6]:
pop = pd.Series([1444,1393,323,278],
               index = ["India","China","USA","Indonesia"],
               name = "Population_millions"
               )

In [7]:
print(pop)

India        1444
China        1393
USA           323
Indonesia     278
Name: Population_millions, dtype: int64

In [8]:
print(pop[pop>500])

India    1444
China    1393
Name: Population_millions, dtype: int64

In [10]:
q1 = pd.Series({"laptops" : 120 , "phones" : 300, "tablets" : 77})
q2 = pd.Series({"phones" : 44,"laptops" : 474 , "tablets" : 73})
print(q1+q2)

laptops    594
phones     344
tablets    150
dtype: int64

In [11]:
##Data frame

In [12]:
df = pd.DataFrame({
    "name" : ["Asha","Bill","Chen","Divya","Evan"],
     "dept" : ["IT","HR","IT","Finance","Hr"],
     "Salary": [52000,48000,47999,75000,50000],
      "city" : ["Delhi","Mumbai","Surat","Agra","Delhi"]
})

In [13]:
print(df)

    name     dept  Salary    city
0   Asha       IT   52000   Delhi
1   Bill       HR   48000  Mumbai
2   Chen       IT   47999   Surat
3  Divya  Finance   75000    Agra
4   Evan       Hr   50000   Delhi

In [17]:
print(df.shape)

(5, 4)

In [15]:
print(list(df.columns))

['name', 'dept', 'Salary', 'city']

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    5 non-null      object
 1   dept    5 non-null      object
 2   Salary  5 non-null      int64
 3   city    5 non-null      object
dtypes: int64(1), object(3)
memory usage: 292.0+ bytes

In [18]:
df.describe()

             Salary
count      5.000000
mean   54599.800000
std    11524.031421
min    47999.000000
25%    48000.000000
50%    50000.000000
75%    52000.000000
max    75000.000000

In [36]:
raw = pd.DataFrame({
    "Order_id" :["1001","1002","1003"],
    "amount" : ["25000", "10000","22000"]
})

In [37]:
print(raw["amount"].sum())

250001000022000

In [38]:
clean = raw.copy()

In [39]:
clean["Order_id"] = pd.to_numeric(clean["Order_id"])
clean["amount"] = pd.to_numeric(clean["amount"])

In [40]:
print(clean.sum())

Order_id     3006
amount      57000
dtype: int64

In [41]:
print(clean["amount"].sum())

57000

In [42]:
df

    name     dept  Salary    city
0   Asha       IT   52000   Delhi
1   Bill       HR   48000  Mumbai
2   Chen       IT   47999   Surat
3  Divya  Finance   75000    Agra
4   Evan       Hr   50000   Delhi

In [43]:
people = df.set_index("name")

In [44]:
people

          dept  Salary    city
name
Asha        IT   52000   Delhi
Bill        HR   48000  Mumbai
Chen        IT   47999   Surat
Divya  Finance   75000    Agra
Evan        Hr   50000   Delhi

In [54]:
print(people.loc["Asha"])

dept         IT
Salary    52000
city      Delhi
Name: Asha, dtype: object

In [55]:
print(people.iloc[1])

dept          HR
Salary     48000
city      Mumbai
Name: Bill, dtype: object

In [56]:
print(people.iloc[0])

dept         IT
Salary    52000
city      Delhi
Name: Asha, dtype: object

In [58]:
print(people.iloc[0:3],[0,2])

     dept  Salary    city
name
Asha   IT   52000   Delhi
Bill   HR   48000  Mumbai
Chen   IT   47999   Surat [0, 2]

In [62]:
print(people[people["Salary"]<49000])

     dept  Salary    city
name
Bill   HR   48000  Mumbai
Chen   IT   47999   Surat

In [73]:
print(people[(people["dept"]=="IT") &(people["Salary"]<49000)])

     dept  Salary   city
name
Chen   IT   47999  Surat

In [76]:
print(people.query("dept == 'IT'"))

     dept  Salary   city
name
Asha   IT   52000  Delhi
Chen   IT   47999  Surat

In [103]:
print(people.query ("dept =='IT' & Salary < 49000"))

     dept  Salary   city
name
Chen   IT   47999  Surat

In [80]:
messy = pd.DataFrame({
    "Product" : ["Pen","Book","Bag","lamp","Mug"],
    "Price" : [20,np.nan,85,1200,np.nan],
    "rating" :[4.1,4.5,np.nan,4.5,3.9]
})

In [81]:
messy

  Product   Price  rating
0     Pen    20.0     4.1
1    Book     NaN     4.5
2     Bag    85.0     NaN
3    lamp  1200.0     4.5
4     Mug     NaN     3.9

In [82]:
messy.isna().sum()

Product    0
Price      2
rating     1
dtype: int64

In [83]:
filled = messy.copy()

In [96]:
filled["Price"]= filled["Price"].fillna(filled["Price"].mean())

In [97]:
filled["rating"]= filled["rating"].fillna(filled["rating"].median())

In [98]:
print(filled)

  Product   Price  rating
0     Pen    20.0     4.1
1    Book    85.0     4.5
2     Bag    85.0     4.3
3    lamp  1200.0     4.5
4     Mug    85.0     3.9